version: '3'

services:
  broker:
    image: netifi/proteus
    environment:
    - "BROKER_SERVER_OPTS=-Dnetifi.broker.admin.accessKey=9007199254740991 -Dnetifi.broker.admin.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY= -Dnetifi.authentication.0.accessKey=9007199254740991 -Dnetifi.authentication.0.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY="
    ports:
    - "6001:6001"
    - "7001:7001"
    - "8001:8001"
    - "8101:8101"
  service:
    image: gregnetifi/proteus-dockertest-service
    environment:
    - "NETIFI_PROTEUS_BROKERHOSTNAME=host.docker.internal"
    depends_on:
    - broker
  client:
    image: gregnetifi/proteus-dockertest-client
    environment:
    - "NETIFI_PROTEUS_BROKERHOSTNAME=host.docker.internal"
    depends_on:
    - broker
