version: '3'

#-Dnetifi.authentication.0.accessKey=3006839580103245170 -Dnetifi.authentication.0.accessToken=SkOlZxqQcTboZE3fni4OVXVC0e0= -Dnetifi.broker.admin.address=host.docker.internal -Dnetifi.broker.admin.publicAddress=host.docker.internal -Dnetifi.broker.admin.port=6001 -Dnetifi.broker.cluster.address=host.docker.internal -Dnetifi.broker.cluster.publicAddress=host.docker.internal -Dnetifi.broker.cluster.port=7001 -Dnetifi.broker.tcp.address=host.docker.internal -Dnetifi.broker.tcp.publicAddress=host.docker.internal -Dnetifi.broker.tcp.port=8001 -Dnetifi.broker.websocket.address=host.docker.internal -Dnetifi.broker.websocket.publicAddress=host.docker.internal -Dnetifi.broker.websocket.port=8101 -Dnetifi.broker.members.address=host.docker.internal:7001
#-Dnetifi.authentication.0.accessKey=3006839580103245170 -Dnetifi.authentication.0.accessToken=SkOlZxqQcTboZE3fni4OVXVC0e0= -Dnetifi.broker.admin.address=host.docker.internal -Dnetifi.broker.admin.publicAddress=host.docker.internal -Dnetifi.broker.admin.port=6002 -Dnetifi.broker.cluster.address=host.docker.internal -Dnetifi.broker.cluster.publicAddress=host.docker.internal -Dnetifi.broker.cluster.port=7002 -Dnetifi.broker.tcp.address=host.docker.internal -Dnetifi.broker.tcp.publicAddress=host.docker.internal -Dnetifi.broker.tcp.port=8002 -Dnetifi.broker.websocket.address=host.docker.internal -Dnetifi.broker.websocket.publicAddress=host.docker.internal -Dnetifi.broker.websocket.port=8102 -Dnetifi.broker.members.address=host.docker.internal:7001
#-Dnetifi.authentication.0.accessKey=3006839580103245170 -Dnetifi.authentication.0.accessToken=SkOlZxqQcTboZE3fni4OVXVC0e0= -Dnetifi.broker.admin.address=host.docker.internal -Dnetifi.broker.admin.publicAddress=host.docker.internal -Dnetifi.broker.admin.port=6003 -Dnetifi.broker.cluster.address=host.docker.internal -Dnetifi.broker.cluster.publicAddress=host.docker.internal -Dnetifi.broker.cluster.port=7003 -Dnetifi.broker.tcp.address=host.docker.internal -Dnetifi.broker.tcp.publicAddress=host.docker.internal -Dnetifi.broker.tcp.port=8003 -Dnetifi.broker.websocket.address=host.docker.internal -Dnetifi.broker.websocket.publicAddress=host.docker.internal -Dnetifi.broker.websocket.port=8103 -Dnetifi.broker.members.address=host.docker.internal:7001

services:
  broker1:
    image: netifi/proteus
    environment:
    - "BROKER_SERVER_OPTS=-Dnetifi.authentication.0.accessKey=3006839580103245170 -Dnetifi.authentication.0.accessToken=SkOlZxqQcTboZE3fni4OVXVC0e0= -Dnetifi.broker.admin.address=host.docker.internal -Dnetifi.broker.admin.publicAddress=host.docker.internal -Dnetifi.broker.admin.port=6001 -Dnetifi.broker.cluster.address=host.docker.internal -Dnetifi.broker.cluster.publicAddress=host.docker.internal -Dnetifi.broker.cluster.port=7001 -Dnetifi.broker.tcp.address=host.docker.internal -Dnetifi.broker.tcp.publicAddress=host.docker.internal -Dnetifi.broker.tcp.port=8001 -Dnetifi.broker.websocket.address=host.docker.internal -Dnetifi.broker.websocket.publicAddress=host.docker.internal -Dnetifi.broker.websocket.port=8101 -Dnetifi.broker.members.address=127.0.0.1:7001"
    ports:
    - "6001:6001"
    - "7001:7001"
    - "8001:8001"
    - "8101:8101"
  broker2:
    image: netifi/proteus
    environment:
    - "BROKER_SERVER_OPTS=-Dnetifi.authentication.0.accessKey=3006839580103245170 -Dnetifi.authentication.0.accessToken=SkOlZxqQcTboZE3fni4OVXVC0e0= -Dnetifi.broker.admin.address=host.docker.internal -Dnetifi.broker.admin.publicAddress=host.docker.internal -Dnetifi.broker.admin.port=6002 -Dnetifi.broker.cluster.address=host.docker.internal -Dnetifi.broker.cluster.publicAddress=host.docker.internal -Dnetifi.broker.cluster.port=7002 -Dnetifi.broker.tcp.address=host.docker.internal -Dnetifi.broker.tcp.publicAddress=host.docker.internal -Dnetifi.broker.tcp.port=8002 -Dnetifi.broker.websocket.address=host.docker.internal -Dnetifi.broker.websocket.publicAddress=host.docker.internal -Dnetifi.broker.websocket.port=8102 -Dnetifi.broker.members.address=127.0.0.1:7001"
    ports:
    - "6002:6002"
    - "7002:7002"
    - "8002:8002"
    - "8102:8102"
    depends_on:
    - broker1
  broker3:
    image: netifi/proteus
    environment:
    - "BROKER_SERVER_OPTS=-Dnetifi.authentication.0.accessKey=3006839580103245170 -Dnetifi.authentication.0.accessToken=SkOlZxqQcTboZE3fni4OVXVC0e0= -Dnetifi.broker.admin.address=host.docker.internal -Dnetifi.broker.admin.publicAddress=host.docker.internal -Dnetifi.broker.admin.port=6003 -Dnetifi.broker.cluster.address=host.docker.internal -Dnetifi.broker.cluster.publicAddress=host.docker.internal -Dnetifi.broker.cluster.port=7003 -Dnetifi.broker.tcp.address=host.docker.internal -Dnetifi.broker.tcp.publicAddress=host.docker.internal -Dnetifi.broker.tcp.port=8003 -Dnetifi.broker.websocket.address=host.docker.internal -Dnetifi.broker.websocket.publicAddress=host.docker.internal -Dnetifi.broker.websocket.port=8103 -Dnetifi.broker.members.address=127.0.0.1:7001"
    ports:
    - "6003:6003"
    - "7003:7003"
    - "8003:8003"
    - "8103:8103"
    depends_on:
    - broker2
  service:
    image: gregnetifi/proteus-dockertest-service
    environment:
    - "NETIFI_PROTEUS_BROKERHOSTNAME=host.docker.internal"
    - "NETIFI_PROTEUS_BROKERPORT=8001"
    - "NETFII_PROTEUS_ACCESSKEY=3006839580103245170"
    - "NETIFI_PROTEUS_ACCESSTOKEN=SkOlZxqQcTboZE3fni4OVXVC0e0="
    depends_on:
    - broker1
    - broker2
    - broker3
  client:
    image: gregnetifi/proteus-dockertest-client
    environment:
    - "NETIFI_PROTEUS_BROKERHOSTNAME=host.docker.internal"
    - "NETIFI_PROTEUS_BROKERPORT=8003"
    - "NETFII_PROTEUS_ACCESSKEY=3006839580103245170"
    - "NETIFI_PROTEUS_ACCESSTOKEN=SkOlZxqQcTboZE3fni4OVXVC0e0="
    depends_on:
    - broker1
    - broker2
    - broker3
