version: '3'

services:
  broker:
    image: netifi/proteus
    environment:
    - "BROKER_SERVER_OPTS=-Dnetifi.authentication.0.accessKey=3006839580103245170 -Dnetifi.authentication.0.accessToken=SkOlZxqQcTboZE3fni4OVXVC0e0="
    ports:
    - "7001:7001"
    - "8001:8001"
  service:
    image: gregnetifi/proteus-dockertest-service
    depends_on:
    - broker
  client:
    image: gregnetifi/proteus-dockertest-client
    depends_on:
    - broker
